spring:
  application:
    name: fileManagerApplication
file:
  upload-dir: /Temp/UploadDir
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 200MB
      max-request-size: 1GB
logging:
  level:
    com.joaojunio.fileManagerApplication: DEBUG

